name: never_again
description: Stop Masturbation And Quit Bad Addictions.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  google_nav_bar: ^3.0.2
  flutter_neumorphic: ^3.0.3
  fl_chart: ^0.12.0
  intl: ^0.16.1
  avatar_glow: ^1.2.0
  provider: ^4.3.2+2
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  font_awesome_flutter: ^8.4.0
  image_picker: ^0.6.7+12
  firebase_storage: ^4.0.1
  shimmer: ^1.1.2
  google_fonts: ^1.1.1
  lottie: ^0.7.0+1
  quotes:
  splashscreen: ^1.2.0
  double_back_to_close_app: ^1.2.0
  shared_preferences: ^0.5.12+2
  google_sign_in: ^4.5.6
  firebase_admob: ^0.10.2






dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - asset/
   - asset/rewards/
#   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

